import { useState } from "react";
import { CheckCircle2, FileText, Sparkles, Thermometer, Verified } from "lucide-react";

// Mock data: replace with GET /api/approvals/:id/sources.
const sources = [
  [FileText, "Drone_Scan_Log_7.json", "Micro-fractures detected. Severity: 0.2mm depth. Quadrant B support structures.", "View Source Document"],
  [Thermometer, "Thermal_Sensor_Array_B.csv", "Delta T of +4.2C observed near coolant valve 3 compared to baseline.", "View Data Visualization"],
];

function Approvals() {
  const [action, setAction] = useState("");

  return (
    <main className="approval-page">
      <header className="approval-header"><div><p className="workspace-label"><Verified size={14} /> Human-in-the-loop Review</p><h1>Inspection Note Authorization</h1></div><div className="approval-actions"><button className="approval-button revision" onClick={() => setAction("Revision requested")}>Request Revision</button><button className="approval-button reject" onClick={() => setAction("Note rejected")}>Reject</button><button className="approval-button approve" onClick={() => setAction("Note approved")}> <CheckCircle2 size={17} /> Approve Note</button></div></header>
      {action && <div className="approval-feedback" role="status">{action}</div>}
      <div className="approval-layout">
        <section className="draft-panel"><div className="draft-heading"><span>Draft Output</span><b><Sparkles size={13} /> Generated by Sovara</b></div><article className="draft-content"><h2>Site Inspection Report: Sector 4 Alpha</h2><p className="draft-meta">Date: 2023-10-27 | Inspector: Automated Drone Unit 7 &amp; Sovara AI Analysis</p><p className="citation">Initial structural scans indicate <mark title="Confidence: 94%">minor micro-fractures</mark> along the primary support beam in Quadrant B. These anomalies are currently within acceptable tolerance levels for industrial operations but warrant continued monitoring over the next fiscal quarter.</p><p>Environmental sensors reported normal atmospheric readings. However, thermal imaging identified an anomalous heat signature near the secondary coolant line.</p><div className="recommendation"><h3>Actionable Recommendation</h3><p>Dispatch engineering team to verify thermal variance at secondary coolant line (Coords: X14.Y9). Schedule preventative maintenance for support beam Quadrant B within 90 days.</p></div></article></section>
        <aside className="evidence-column"><section className="confidence-card"><h2>Analysis Confidence</h2><Confidence label="Structural Assessment" value="94%" width="94%" /><Confidence label="Thermal Anomaly Verification" value="78%" width="78%" muted /></section><section className="sources-card"><div className="sources-heading">Audit Trail &amp; Sources</div><div className="source-list">{sources.map(([Icon, name, text, link]) => <article className="approval-source" key={name}><div><Icon size={16} /><span>{name}</span></div><p>“{text}”</p><button>{link}</button></article>)}</div></section></aside>
      </div>
    </main>
  );
}

function Confidence({ label, value, width, muted }) {
  return <div className="confidence-row"><div><span>{label}</span><b className={muted ? "muted" : ""}>{value}</b></div><div className="confidence-track"><i className={muted ? "muted" : ""} style={{ width }} /></div></div>;
}

export default Approvals;
